### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by cflewis**
Fake PR for testing.

---
This change is [Reviewable](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2)

### CODE REVIEW

**Comment by cflewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[README.markdown, line 5 at r1](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2#-LDHuHlD-EV3hmTtpCtX:-LDHuHlD-EV3hmTtpCtY:bhkk75m) ([raw file](https://github.com/cflewis/infinite-mario-bros/blob/688f60ac4ab9c2f41116c9e1750c0efecbd67314/README.markdown#L5)):*
> ```Markdown
> [Infinite Mario Bros](http://www.mojang.com/notch/mario/) source code has a bug in the timing, which prevents it working on Mac OS X, and maybe other platforms. This version uses the timing from the Mario AI competition, and is Mac-compatible.
> 
> Fake PR
> ```

This is wrong.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2)*

**Comment by cflewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.markdown, line 5 at r1](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2#-LDHuHlD-EV3hmTtpCtX:-LDHuXsWAce2KtGCDarC:b-896fix) ([raw file](https://github.com/cflewis/infinite-mario-bros/blob/688f60ac4ab9c2f41116c9e1750c0efecbd67314/README.markdown#L5)):*
<details><summary><i>Previously, cflewis (Chris Lewis) wrote…</i></summary><blockquote>

This is wrong.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2)*

**Comment by cflewis** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2)*

**Comment by zombiezen** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2#-:-LDHvQncAiqyIx4Lkulj:bnfp4nl)*

**Comment by cflewis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.markdown, line 5 at r1](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2#-LDHuHlD-EV3hmTtpCtX:-LDHvuxc5LOYUz_ZPqGg:b-896fix) ([raw file](https://github.com/cflewis/infinite-mario-bros/blob/688f60ac4ab9c2f41116c9e1750c0efecbd67314/README.markdown#L5)):*
<details><summary><i>Previously, cflewis (Chris Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2)*

**Comment by zombiezen** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[README.markdown, line 5 at r1](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2#-LDHuHlD-EV3hmTtpCtX:-LDHvzFsEaO56b4kuKDN:b32w0x) ([raw file](https://github.com/cflewis/infinite-mario-bros/blob/688f60ac4ab9c2f41116c9e1750c0efecbd67314/README.markdown#L5)):*
<details><summary><i>Previously, cflewis (Chris Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/cflewis/infinite-mario-bros/2)*

**Pull request merged**
